### ISSUE TITLE
Callback for SPTAppRemotePlayerAPI pause() method never returns.

### ISSUE THREAD

**Issue by mrpossoms** [spotify/ios-app-remote-sdk#2]
* remote-sdk version 1.0.0
* Spotify version 8.4.51
* iPhone SE
* iOS 11.3

Calling pause() on a valid SPTAppRemotePlayerAPI instance with an open connection properly pauses playback, but the callback never returns with a result or error object.

Also, once the playback has paused, the connection closes. Attempting to call connect() on the SPTAppRemotePlayerAPI object never reconnects. Alternatively, attempting to reauthorize also does not allow reconnection.

**Comment by kafejo** [comment]
Any update on this? This is really annoying as there's no way to resume playback once user pauses the player.

**Comment by jackfreeman** [comment]
Currently, when audio is paused the Spotify app is suspended in the background. This requires an app switch to resume playing music using the `authorizeAndPlayURI:` API.  There is no player state callback after calling pause as the connection to the Spotify app has been terminated. Please see the included demo app and how it handles resuming playback after a pause. I also recommend checking out our [Application Lifecycle Guide](https://beta.developer.spotify.com/documentation/ios-app-remote/guides/application-lifecycle/) for more info on when to connect and disconnect App Remote.

This behavior is subject to change, so you should monitor connection states instead of assuming a pause will always result in a disconnect.

**Comment by Ge0rges** [comment]
Hello,

I'm wondering how is one meant to implement a Play/Pause button? Are we expected to call `authorizeAndPlayURI ` after the user pauses music for any action (such as skip)? And if so why does the `resume` function exist.
